### ISSUE TITLE
EXT-8 Support for Arduino (Teensy 4) built binaries?

### ISSUE THREAD

**Issue by ripe909** [JayHeng/NXP-MCUBootUtility#58] opened 2019-01-07 19:49 UTC
Teensy 4 is based on the IMXRT1050/60 and they have started beta development of the toolchain.  I'm not sure how feasible or necessary it is, but it would be interesting to support the hex/elf output files from the Arduino build output.

**Comment by JayHeng** [comment] 2019-01-08 06:03
Is Teensy4 board name or toolchain name? NXP-MCUBootUtility is board-independent, it should support all kinds of i.MXRT boards, because tool only talk with the onchip ROM of i.MXRT. and for binary format, hex/srec/bin are common formats, they are toolchain-independent.

The only issue is elf file from dedicate toolchain, if it is not common GNU ELF format, NXP-MCUBootUtility may not support it.

**Comment by ripe909** [comment] 2019-01-08 13:18
Arduino/Teensy4 uses GCC, I am attaching a Blinky example .elf file built from Arduino using the Teensy 4 core.  I tried reading it in MCUBootUtility unsuccessfully.
[Blink.pde.elf.zip](https://github.com/JayHeng/NXP-MCUBootUtility/files/2736885/Blink.pde.elf.zip)

**Comment by JayHeng** [comment] 2019-01-08 15:50
the same root cause as your last question, this elf file contains i.MXRT headers

**Comment by ripe909** [comment] 2019-01-08 15:52
cool, I may wait for your future updates then.  In general the Arduino build can't/shouldn't be changed.

I also saw your blog postings (via Google translate)  they are very good and helpful!

**Comment by JayHeng** [comment] 2019-01-08 15:56
so it seems to be a very common issue, v1.1 will be released by end of this week

**Closed** 2019-01-25 01:11 UTC
Labels: user service (Q&A)
